version: "3.8"
services:
  exporter:
    image: egnd/docker-events-exporter:local
    build: .
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    ports:
      - 80:8080
