name: Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  todos:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - run: make _ci-todos
  conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make _ci-conflicts
  gitflow:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'master')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make _ci-master
  
  build:
    runs-on: ubuntu-latest
    needs: [todos, conflicts]
    env:
      JOB_IMAGE: egnd/docker-events-exporter
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DHLGN }}
          password: ${{ secrets.DHPWD }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{env.JOB_IMAGE}}:latest,${{env.JOB_IMAGE}}:${{env.RELEASE_VERSION}}
          cache-from: ${{env.JOB_IMAGE}}:latest
